In [1]:
import pandas as pd

data=pd.read_csv("/Users/akshayy/Documents/Ineuron/Datasets/winequality-red.csv",sep=",")

In [2]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
data.shape

(1599, 12)

In [4]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(data)

In [5]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1511,7.1,0.690,0.04,2.10,0.068,19.0,27.0,0.99712,3.44,0.67,9.8,5
1044,6.4,0.390,0.33,3.30,0.046,12.0,53.0,0.99294,3.36,0.62,12.2,6
1584,6.7,0.320,0.44,2.40,0.061,24.0,34.0,0.99484,3.29,0.80,11.6,7
1321,5.0,0.740,0.00,1.20,0.041,16.0,46.0,0.99258,4.01,0.59,12.5,6
539,11.2,0.500,0.74,5.15,0.100,5.0,17.0,0.99960,3.22,0.62,11.2,5
...,...,...,...,...,...,...,...,...,...,...,...,...
215,7.0,0.490,0.49,5.60,0.060,26.0,121.0,0.99740,3.34,0.76,10.5,5
1336,6.0,0.500,0.00,1.40,0.057,15.0,26.0,0.99448,3.36,0.45,9.5,5
1292,5.9,0.395,0.13,2.40,0.056,14.0,28.0,0.99362,3.62,0.67,12.4,6
1339,7.5,0.510,0.02,1.70,0.084,13.0,31.0,0.99538,3.36,0.54,10.5,6
1376,8.2,0.885,0.20,1.40,0.086,7.0,31.0,0.99460,3.11,0.46,10.0,5

In [6]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1377,5.2,0.49,0.26,2.30,0.090,23.0,74.0,0.99530,3.71,0.62,12.2,6
621,8.2,0.56,0.23,3.40,0.078,14.0,104.0,0.99760,3.28,0.62,9.4,5
1592,6.3,0.51,0.13,2.30,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1559,7.8,0.60,0.26,2.00,0.080,31.0,131.0,0.99622,3.21,0.52,9.9,5
357,10.5,0.42,0.66,2.95,0.116,12.0,29.0,0.99700,3.24,0.75,11.7,7
...,...,...,...,...,...,...,...,...,...,...,...,...
741,9.2,0.53,0.24,2.60,0.078,28.0,139.0,0.99788,3.21,0.57,9.5,5
660,7.2,0.52,0.07,1.40,0.074,5.0,20.0,0.99730,3.32,0.81,9.6,6
408,10.4,0.34,0.58,3.70,0.174,6.0,16.0,0.99700,3.19,0.70,11.3,6
1121,6.6,0.50,0.00,1.80,0.062,21.0,28.0,0.99352,3.44,0.55,12.3,6
83,7.3,0.67,0.26,1.80,0.401,16.0,51.0,0.99690,3.16,1.14,9.4,5

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import ElasticNet

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,accuracy_score,roc_auc_score
from sklearn.model_selection import  train_test_split

In [8]:
X_train=train.drop(["quality"],axis=1)
X_test=test.drop(["quality"],axis=1)
    
y_train=train[["quality"]]
y_test=test[["quality"]]

In [9]:
rf=RandomForestClassifier()
rf.fit(X_train, y_train)

/Users/akshayy/mlflow1/env/lib/python3.8/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier()

In [10]:
X_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
1377,5.2,0.49,0.26,2.30,0.090,23.0,74.0,0.99530,3.71,0.62,12.2
621,8.2,0.56,0.23,3.40,0.078,14.0,104.0,0.99760,3.28,0.62,9.4
1592,6.3,0.51,0.13,2.30,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1559,7.8,0.60,0.26,2.00,0.080,31.0,131.0,0.99622,3.21,0.52,9.9
357,10.5,0.42,0.66,2.95,0.116,12.0,29.0,0.99700,3.24,0.75,11.7
...,...,...,...,...,...,...,...,...,...,...,...
741,9.2,0.53,0.24,2.60,0.078,28.0,139.0,0.99788,3.21,0.57,9.5
660,7.2,0.52,0.07,1.40,0.074,5.0,20.0,0.99730,3.32,0.81,9.6
408,10.4,0.34,0.58,3.70,0.174,6.0,16.0,0.99700,3.19,0.70,11.3
1121,6.6,0.50,0.00,1.80,0.062,21.0,28.0,0.99352,3.44,0.55,12.3
83,7.3,0.67,0.26,1.80,0.401,16.0,51.0,0.99690,3.16,1.14,9.4

In [11]:
pred_prob=rf.predict_proba(X_test)

In [12]:
roc_auc_score=roc_auc_score(y_test,pred_prob,multi_class='ovr')

In [13]:
roc_auc_score

0.829104364681764